### ISSUE TITLE
Driver wants to convert shape to wrong type 

### ISSUE THREAD

**Issue by rs-idesis** [edgedb/edgedb-net#47]
**Describe the bug**
A select query with links to shapes of different types but the of the same base type, like author and director of movies being all persons, results in conversion errors as long as the shapes' fields are queried in exactly the same way (same fields in the same order):

```
Exception source: EdgeDB.Net.Driver
EdgeDB.EdgeDBException: Failed to deserialize object to DB.Model.Movies.Movie
 ---> System.ArgumentException: Cannot convert DB.Model.Movies.Director to type DB.Model.Movies.Actor
   at EdgeDB.ObjectBuilder.ConvertTo(Type type, Object value)
   at ...
   --- End of inner exception stack trace ---
   at EdgeDB.Binary.Codecs.ObjectCodec.Deserialize(PacketReader& reader, CodecContext context)
   at EdgeDB.TypeBuilder.BuildObject(EdgeDBBinaryClient client, Type type, ObjectCodec codec, Data& data)
  ...
```

**Reproduction**
The following query, where actors and directors are defined in the same way, cause the exception. As soon as the order of one shape is changed, everything is working.

```
        var query = $$"""
            select Movie {
                id,
                title,
                year,
                description,
                actors: {
                    id,
                    full_name,
                    first_name,
                    middle_name,
                    last_name,
                    image,
                    dod,
                    dob,
                    bio,
                    @list_order
                },
                directors: {
                    id,
                    full_name,
                    first_name,
                    middle_name,
                    last_name,
                    image,
                    dod,
                    dob,
                    bio,
                    @list_order
                }
            };
            """;
        await _Client.QueryAsync<Movie?>(query);
```
A full example with schema and db content can be found [here](https://github.com/idesis-gmbh/Issues.EdgeDB.Driver.Select).

**Expected behavior**
Shapes should be converted to the correct object type, regardless of "field randomisation".

**Versions (please complete the following information):**

- OS: macOS Monterey 12.5.1
- EdgeDB version: 2.14+5561c9b
- EdgeDB CLI version: 2.3.1+5d93f42
- `edgedb-net` version: 1.1.3
- .NET version: 7.0.203

**Comment by quinchs** [comment]
This bug is caused by the codec cache, essentially:
- client asks EdgeDB to describe the result of the query[^1]
- server returns *one* descriptor for both `Actor` and `Director` since they use the same shape
- client creates *one* codec for both `Actor` and `Director`
- client initializes this codec with the .NET type information `Movie`[^2], when it initializes the `Movie.actors` property, it changes the *one* codec responsible for deserializing `.actors` state, then it initializes the `Movie.directors` property, overriding the *one* codecs state to be for the .NET `Director` type, causing `.actors` to be treated as a `Director`


My initial thoughts on how to fix this is to clone non-scalar codecs that show up more than once under different property names, I'll continue looking for a fix

[^1]: https://www.edgedb.com/docs/reference/protocol/messages#parse
[^2]: https://github.com/edgedb/edgedb-net/blob/dev/src/EdgeDB.Net.Driver/Binary/Codecs/Visitors/TypeVisitor.cs#L59-L92
